### ISSUE TITLE
Need method to get referenceNames for variant set

### ISSUE THREAD

**Issue by jrobinso** [ga4gh/schemas#222]
Hi, apologize for creating so many issues, if there is a better forum for discussion or these are not appropriate please let me know.

In order to retrieve variants from a variant set you need to know the reference names in the set.   However, there is no API call to retrieve them (the reference names used in the set).  I've observed that GAVariantSetMetadata has this information in a "referenceBounds" object for at least some of the sets I've tested, but this isn't guaranteed.   It would be immensely helpful to have  a required field, probably in GAVariantSetMetadata or perhaps just GAVariantSet, that references the GAReferenceSet the variants are aligned to.   Alternatively, a sequence dictionary (reference name + length), or just a list of reference names would suffice.

I notice that the alignment API does require this information,  the GAReadGroup must reference a GAReferenceSet if alignments are included.   This is a good rule for any collection of genomic entities with positions, that they reference the GAReferenceSet the positions refer to.

This is important for genome browsers, and probably other applications, because there aren't standards for chromosome names.   I'm thinking specifically of "1" vs "chr1",  but this problem recurs across other organisms and assemblies.   

I'm aware that VCF doesn't have this, but to query a VCF file you must have an index (usually tabix), and the information is in the index file.   So there is a method to determine the reference names for every queryable (i.e. indexed) VCF file.   Removing this capability in ga4gh is thus a step backwards.

Thoughts about this?

**Comment by calbach** [comment]
Thanks Jim for filing these issues, I think this is the right place for them and this is very useful feedback. Many of the issues you're raising are due to mismatch between GA4GH and Google API semantics, so I'll attempt to route the Google-implementation specific issues to a more Google-specific venue.

I believe the GA4GH API answer here is to acquire the `variantSet.referenceSetId`, then use this ID to do `SearchReferences(referenceSetId="..")`. This field unfortunately also wasn't part of the [v0.5.1 API](http://ga4gh.org/documentation/api/v0.5.1/ga4gh_api.html#/schema/org.ga4gh.GAVariantSet). If this satisfies your needs I think this particular issue can be closed.

The Google Genomics API doesn't currently define this field, unfortunately, but that's a feature request for our API. The `referenceBounds` field is specific to the Google implementation and is the stop-gap until reference set support is added, though I'm surprised you found variant sets which lack it and I'd be interested in seeing them. I filed https://github.com/googlegenomics/api-client-java/issues/66 on our end to support `referenceSetId` as defined in the GA4GH API.

**Comment by jrobinso** [comment]
Ahh, perfect, yes variantSet.refererenceSetId seems like the right way to do this.  I'll close this now.
