### ISSUE TITLE
Best method for supporting multiple assemblies in Matchmaker API?

### ISSUE THREAD

**Issue by buske** [ga4gh/schemas#223]
Hi all,

I wanted to solicit feedback from the Variation Task Team and anyone else on advice for supporting/describing reference assemblies within the Matchmaker API.

When a match request is sent, candidate genes and variant information can be provided to contribute to the matching. At present, each variant is associated with an assembly of the form: "NCBI36", or "GRCh37.p13". We have not yet placed any constraints on the assemblies in the match request, the assemblies in the match response, or how they relate to each other. 

Any suggestions given your experiences so far? Thanks!

**Comment by deannachurch** [comment]
Are you saying that people can just give a chromosome coordinate to do the match? That will get a LOT of false matches. 

WRT to assembly information, I'd start with the NCBI assembly database- here is the page for GRCh38:
http://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.26
This provides data on the canonical naming and sequence identifiers. 

You can use the NCBI remap service: http://www.ncbi.nlm.nih.gov/genome/tools/remap
to get location equivalencies between assemblies. 

I think the easiest thing to do is map all variants onto each assembly you want to report and store those locations. Then you can return the variant in whatever genomic context the requestor wants.

**Comment by buske** [comment]
Not quite. Ideally, people provide both phenotypic and genotypic features for a patient. In the most degenerate case, they could give a single gene name, or a single chromosomal coordinate, but the matches would likely be poor, if they are given at all.

The idea is that genotypic features can be specified at varying resolutions (e.g. gene name, or assembly/chromosome/position). Thank you for the links. NCBI remap looks like a great resource, though it didn't look set up for real-time liftover in the way that would allow us to convert the incoming queries in real time as pre-processing.

It sounds like you're vote is to instead have the requestor specify the desired assembly of the response (and presumably provide all their variants on that assembly as well), and having the server store all variants in all assemblies internally, so the matching can be done on whatever assembly the requestor desires?

**Comment by deannachurch** [comment]
Sorry- maybe I don't understand enough of this process. I was just reacting to the coordinate issue- if you specify a variant by coordinate (1:459300) then you MUST provide an assembly context or it is meaningless. For users searching by variant position, they would need to specify a specific assembly or you have no idea how to search. The scary part about this is you likely will get an answer regardless of the assembly context so it makes errors very hidden. Just this morning I got mislead as I ran my GRCh37 variant data through the GRCh38 VEP and got results- but they were all wrong. That is the coordinate pointed to different genes depending one whether I was on 37 or 38.  I have a teaching exercise where I demonstrate how easy it is to upload the wrong data to the UCSC browser (e.g. NCBI36 data on GRCh37). 
For return of results, you don't have to require users to specify an assembly, but you need to be clear about the assembly you are using if you return coordinates. Letting users specify a specific assembly to have results returned on is a nice feature, but does put a bigger burden on you to maintain resources on multiple assemblies. In my experience, it is useful to be explicit about this as many users don't understand the issues of shifting coordinates between assemblies because they don't actually think that much about the assembly.
NCBI remap is great for pre-processing data you already have, but you are correct, they can't do an on the fly translation. It may be worthwhile asking if they could provide such an endpoint. 
Hope that is helpful! I'm pretty interested in learning more about this.

**Comment by fschiettecatte** [comment]
I use http://genome.ucsc.edu/cgi-bin/hgLiftOver for lifts, I wrote a simple wrapper in python which provides a simple API within GeneMatcher. It is fast enough for my purposes but I have not tested it with large numbers of coordinate. Maybe they could be persuaded to provide this as an API?

**Comment by deannachurch** [comment]
There are some subtleties of coordinate remapping the LiftOver does not handle well, though for most things you care about now this might work well enough. You could also use the Ensembl REST API for this. http://rest.ensembl.org/documentation/info/assembly_map
I don't know a lot about they methods they use for alignment, but for ease of use, there is already an API. The trick is learning to deal with the odd ball cases.

**Comment by mbaudis** [comment]
LiftOver is good e.g. if you have array data you want to remap & don’t care for some losses (we use it for arraymap.org <http://arraymap.org/> raw data); however, you don’t get all of the co-ordinates (e.g. we don’t do it for region re-mapping) if considering “non-genome-object” regions.

**Comment by buske** [comment]
@fschiettecatte I agree.

Anyone at UCSC willing to speak to the feasibility of setting up a real-time AJAX liftover resource with high uptime that APIs could utilize? It would need to handle the complexities of lifting over alleles, of course.

E.g. input: 
```json
{
  "fromAssembly" : "NCBI36", 
  "toAssembly" : "GRCh37",
  "referenceName" : "chr1",
  "position" : 12345,
  "ref" : "A",
  "alt" : "ACCC"
}
```

Output (assuming inversion in this region between 36 and 37, and the reference in 36 is `AG` (insertion of `CCC`), and in 37 is `CT` (insertion of `GGG`):
```json
{
  "assembly" : "GRCh37",
  "referenceName" : "chr1",
  "position" : 67890,
  "ref" : "C",
  "alt" : "CGGG"
}
```

**Comment by diekhans** [comment]
This could be something we could explore at UCSC, however NCBI already
has a service:

    http://www.ncbi.nlm.nih.gov/genome/tools/remap/docs/api

liftover would be a good API for G4GH to define.  That would
make it far easier for use to justify at UCSC.

Unfortunately, the answers are only as good as the underlying
alignments, and that is still not solved problem.

**Comment by lh3** [comment]
To implement liftOver APIs, we need to first have APIs for the reference genome. It *might* be a good idea to separate and stabilize reference genome APIs first such that endusers could have a uniform interface to get reference information (e.g. subsequences, md5, accession numbers, liftover albeit different, etc) from ucsc/ensembl/ncbi. I always wish that could happen. Just a random thought.

**Comment by diekhans** [comment]
+100 ;-)

**Comment by buske** [comment]
Thank you for all the helpful suggestions!
