### ISSUE TITLE
Sphinx documentation generator duplicates documentation

### ISSUE THREAD

**Issue by diekhans** [ga4gh/schemas#425]
Documentation  from included files gets included in each page rather than referencing them.  For instance:

```
http://hgwdev.cse.ucsc.edu/~markd/ga4gh/documentation-pr/schemas/metadata.html
```

copies data from common.

**Comment by diekhans** [comment]
We need to decide if this should be fixed now or wait until the protobuf switch

**Comment by hjellinek** [comment]
It does, and I'm really not sure how to fix it.

**Comment by diekhans** [comment]
We might have to write are own avro parser for this.  Although
it might not be necessary if we switch to protobug.

**Comment by mbaudis** [comment]
> protobug

Hmm, is this intentional?

I’ve written a "just get records and their attributes” parser for http://progenetix.org/codedisplay/?codepage=http://github.com/ga4gh/schemas/raw/metadata/src/main/resources/avro/metadata.avdl <http://progenetix.org/codedisplay/?codepage=http://github.com/ga4gh/schemas/raw/metadata/src/main/resources/avro/metadata.avdl>

…

So no big deal if someone is not it. But then, someone has to host it, so responsibilities.

**Comment by hjellinek** [comment]
Hi @reece, you might want to have a look at this while plumbing the depths of our Sphinx configuration.

**Comment by reece** [comment]
There's no easy way to fix this. The fact that some params were included from common.avdl is lost in the first conversion step. The only way I see to fix it is to write custom code to replace the common params block with a reference to the derived common.rst.

Given that we're moving to protobuf and will have new doc issues to work out, I suggest that we close this issue and move on.

**Comment by diekhans** [comment]
completely agree; although leaving open until we are official decided to move to protbuf.

**Comment by david4096** [comment]
Closed with https://github.com/ga4gh/schemas/pull/634
