### ISSUE TITLE
Consistent and rich type representation in info fields

### ISSUE THREAD

**Issue by diekhans** [ga4gh/schemas#607]
GA4GH API needs a common representation for generic
attribute/value data in objects (info fields) that handles more
than string types.

Many GA4GH objects have generic key/value pairs to
accommodate arbitrary data that is not modeled.  This
is viewed as an important feature for a data exchange API
built on existing date sets.  This is represented as a map
of array of strings in several objects:

  map<array<string>> info = {};

This handles both multiple instances of an attribute name and
multi-part attribute values. well when the values are strings.
It's also a fairly straight-forward conversion to numeric
values.

There are several structure types that will be part that are
going to be common to multiple parts of the of GA4GH.  Currently
define are:
- ExternalIdentifier  https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/common.avdl#L41
- OntologyTerm  https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/metadata.avdl#L11

These types of external linkage will be something one wants to
include in the keyword/value info fields.  In a modern
programming language, this might be implemented by making the
values a polymorphic objects.  However, neither Avro nor Protocol
Buffers support true polymorphic data structures.

The SequenceAnnotations Feature object works around this by using
a union data structure (analogous to C-style unions):

```
map<array<union {string, ExternalIdentifier, OntologyTerm}>> info = {};
```

In Protocol Buffers, this would be implemented using the `oneof'
of construct.

Some concern has been expressed over this construct being confusing.

It would be good to here other solutions on how to represent
un-modeled data in a semi-structured manner.

This is related to https://github.com/ga4gh/schemas/issues/445,

**Comment by richarddurbin** [comment]
Yes.  This is important.  I think we should be able to strongly type the value component of key/value pairs,
as in VCF or BAM.  That is there should a declaration that states which keys are allowed, and for each key what
the type of the value is, including scalars, fixed length tuples, and open ended arrays.  I hear that this is not
provided by AVRO or Protobuf, but nor is it by plain text or binary files - we just developed a specification and
parsing code ourselves.  Of course it would be nice to do this in as standard a way as possible.  

I am to be honest surprised that nobody else has had this problem of representing polymorphic-valued information 
in protobuf.  Surely someone in Google has had to deal with this issue before, and there is something approaching
standard practice.  One solution may be to use the union structure that Mark describes as being specified for the 
SequenceAnnotations Feature object.  At the lowest level we could just have a string and parse it, but that is
clearly very inefficient and negates a fair bit of the benefit of protobuf over avro. Certainly it would be good for 
GA4GH to adopt a standard solution.

Richard

Mark: I am copying you directly because I have had some problems with Google permissions.  If this doesn’t
get forwarded to the group mailing list perhaps you could do that for me.

> On 5 Apr 2016, at 23:50, Mark Diekhans <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> GA4GH API needs a common representation for generic
> attribute/value data in objects (info fields) that handles more
> than string types.
> 
> Many GA4GH objects have generic key/value pairs to
> accommodate arbitrary data that is not modeled. This
> is viewed as an important feature for a data exchange API
> built on existing date sets. This is represented as a map
> of array of strings in several objects:
> 
> map> info = {};
> 
> This handles both multiple instances of an attribute name and
> multi-part attribute values. well when the values are strings.
> It's also a fairly straight-forward conversion to numeric
> values.
> 
> There are several structure types that will be part that are
> going to be common to multiple parts of the of GA4GH. Currently
> define are:
> 
> ExternalIdentifier https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/common.avdl#L41 <https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/common.avdl#L41>
> OntologyTerm https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/metadata.avdl#L11 <https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/metadata.avdl#L11>
> These types of external linkage will be something one wants to
> include in the keyword/value info fields. In a modern
> programming language, this might be implemented by making the
> values a polymorphic objects. However, neither Avro nor Protocol
> Buffers support true polymorphic data structures.
> 
> The SequenceAnnotations Feature object works around this by using
> a union data structure (analogous to C-style unions):
> 
> map<array<union {string, ExternalIdentifier, OntologyTerm}>> info = {};
> In Protocol Buffers, this would be implemented using the `oneof'
> of construct.
> 
> Some concern has been expressed over this construct being confusing.
> 
> It would be good to here other solutions on how to represent
> un-modeled data in a semi-structured manner.
> 
> This is related to #445 <https://github.com/ga4gh/schemas/issues/445>,
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/ga4gh/schemas/issues/607>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
